spring:
  redis:
    host: localhost
    port: 6379      
zuul:
  sensitive-headers:
  routes:
    myproduct:
#     /myProduct/product/list -> /product/product/list
      path: /myproduct/**
      serviceId: poduct
#    简洁写法
#    product: /myProduct/**
#  排除某些路由,可配置多个
  ignored-patterns:
    - /**/product/listForOrder
#    - /product/product/listForOrder
#    - /myproduct/product/listForOrder
  
# 电脑有点卡，ribbon会超时异常，需配置以下ribbon  
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000


server:
  port: 6000
env: dev
