
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 17307867
  jpa:
    show-sql: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  redis:
    port: 6379
    host: localhost
    
env: dev
boy:
  age:  1810
  name: xiao
server:
  port: 6001
  
logging:
  level:
   org.springframework.cloud.netflix.feign: debug
