
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 17307867
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  redis:
    port: 6379
    host: localhost
    
env: dev 
server:
  port: 6001
